export const movieData = {
  dates: {
    maximum: "2023-07-25",
    minimum: "2023-06-07",
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/llZSAx6YW0y9tV4iMKmbUBNh70I.jpg",
      genre_ids: [35, 12, 14],
      id: 346698,
      original_language: "en",
      original_title: "Barbie",
      overview:
        "원하는 무엇이든 될 수 있는 '바비랜드'에서 살아가던 '바비'가 현실 세계와 이어진 포털의 균열을 발견하게 되고, 이를 해결하기 위해 '켄'과 예기치 못한 여정을 떠나면서 펼쳐지는 이야기",
      popularity: 2068.341,
      poster_path: "/rt8sHzR0XUyKHxU75ZIWs7MsNEN.jpg",
      release_date: "2023-07-19",
      title: "바비",
      video: false,
      vote_average: 8.2,
      vote_count: 107,
    },
    {
      adult: false,
      backdrop_path: "/xGIeqQunSj5dxGZVKzNNr9W4vps.jpg",
      genre_ids: [28, 12, 878],
      id: 298618,
      original_language: "en",
      original_title: "The Flash",
      overview:
        "시공간이 붕괴된 세계, 차원이 다른 히어로가 온다! 빛보다 빠른 스피드, 물체 투과, 전기 방출, 자체 회복, 천재적인 두뇌까지 갓벽한 능력을 자랑하지만 존재감은 제로, 저스티스 리그에서 궂은일을 도맡아 하는 히어로 ‘플래시’. 어느 날 자신에게 빛보다 빠른 속도로 달리면 시공간 이동 능력이 있음을 알게 된 그는 ‘브루스 웨인’의 만류를 무시한 채 끔찍한 상처로 얼룩진 과거를 바꾸기 위해 시간을 역행한다. 의도치 않은 장소에 불시착한 ‘플래시’는 멀티버스 세상 속 또 다른 자신과 맞닥뜨리고 메타 휴먼이 흔적도 없이 사라지고 모든 것이 뒤엉킨 세상과 마주하게 된다. ‘플래시’는 자신이 알던 모습과 전혀 달라진 나이 들고 은퇴한 ‘배트맨’과 크립톤 행성에서 온 ‘슈퍼걸’의 도움으로 외계의 침공으로부터 시간과 차원이 붕괴된 지구를 구하려 나서는데…",
      popularity: 2118.682,
      poster_path: "/muD7qu9UagO08dZBout1YXwdE6a.jpg",
      release_date: "2023-06-14",
      title: "플래시",
      video: false,
      vote_average: 6.9,
      vote_count: 1128,
    },
    {
      adult: false,
      backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
      genre_ids: [28, 12, 16, 878],
      id: 569094,
      original_language: "en",
      original_title: "Spider-Man: Across the Spider-Verse",
      overview:
        "여러 성장통을 겪으며 새로운 스파이더맨이 된 마일스 모랄레스. 그 앞에 다른 평행세계의 스파이더우먼 그웬이 다시 나타난다. 모든 차원의 멀티버스 속 스파이더맨들을 만나게 되지만, 질서에 대한 신념이 부딪히며 예상치 못한 균열이 생기는데… 상상 그 이상을 넘어서는 멀티버스의 세계가 열린다!",
      popularity: 1181.02,
      poster_path: "/zG9TYiHt0fdaJiWuNEhFrfKzwoi.jpg",
      release_date: "2023-06-21",
      title: "스파이더맨: 어크로스 더 유니버스",
      video: false,
      vote_average: 8.5,
      vote_count: 2348,
    },
    {
      adult: false,
      backdrop_path: "/cSYLX73WskxCgvpN3MtRkYUSj1T.jpg",
      genre_ids: [16, 35, 10751, 14, 10749],
      id: 976573,
      original_language: "en",
      original_title: "Elemental",
      overview:
        "불, 물, 공기, 흙 4개의 원소들이 살고 있는 엘리멘트 시티. 재치 있고 불처럼 열정 넘치는 앰버는 어느 날 우연히 유쾌하고 감성적이며 물 흐르듯 사는 웨이드를 만나 특별한 우정을 쌓으며, 지금껏 믿어온 모든 것들이 흔들리는 새로운 경험을 하게 되는데...",
      popularity: 1061.173,
      poster_path: "/1YYL1OcgjPLjAGi6n0iZe1gdl9i.jpg",
      release_date: "2023-06-14",
      title: "엘리멘탈",
      video: false,
      vote_average: 7.6,
      vote_count: 521,
    },
    {
      adult: false,
      backdrop_path: "/2fTmypmAAfyQu6NxVB0MtBLVU6Z.jpg",
      genre_ids: [28, 53, 12],
      id: 575264,
      original_language: "en",
      original_title: "Mission: Impossible - Dead Reckoning Part One",
      overview:
        "모든 인류를 위협할 새로운 무기를 추적하게 된 에단 헌트와 IMF팀은 이 무기가 인류의 미래를 통제할 수 있다는 사실을 알게 된다. 전 세계가 위태로운 상황에 처한 가운데, 이를 추적하던 에단 헌트에게 어둠의 세력까지 접근하고 마침내 미스터리하고 강력한 빌런과 마주하게 된 그는 가장 위험한 작전을 앞두고 자신이 아끼는 사람들의 생명과 중요한 임무 사이에서 선택을 해야 하는 상황에 놓이게 되는데…",
      popularity: 735.929,
      poster_path: "/nQsWPG020kSWdOl3EhFXRNE2s0n.jpg",
      release_date: "2023-07-12",
      title: "미션 임파서블: 데드 레코닝 PART ONE",
      video: false,
      vote_average: 7.9,
      vote_count: 486,
    },
    {
      adult: false,
      backdrop_path: "/hPcP1kv6vrkRmQO3YgV1H97FE5Q.jpg",
      genre_ids: [27, 9648, 53],
      id: 614479,
      original_language: "en",
      original_title: "Insidious: The Red Door",
      overview:
        "10년 전, 유체이탈을 통해 기이한 사건을 겪은 '조쉬'와 '달튼' 부자는 그날의 기억을 모두 지운다. 10년 후,'조쉬'는 수상한 존재가 주변을 맴돌고 있음을 느끼고, 집을 떠나 대학에 입학한 ‘달튼'은 봉인된 기억 속 빨간 문에 대한 의문을 품게 된다. 램버트 가족에게 연달아 기괴한 사건들이 일어나고 과거의 비밀이 끔찍한 악몽으로 되살아나는데…",
      popularity: 664.252,
      poster_path: "/4UCQWDmMsOxqgtdTbkihSXbexbf.jpg",
      release_date: "2023-07-19",
      title: "인시디어스: 빨간 문",
      video: false,
      vote_average: 6,
      vote_count: 189,
    },
    {
      adult: false,
      backdrop_path: "/sbtJ1SxJ1CIvttQqhGbUZcDpSqC.jpg",
      genre_ids: [35, 10749, 878],
      id: 747188,
      original_language: "en",
      original_title: "Asteroid City",
      overview:
        "1955년 가상의 사막 도시이자 운석이 떨어진 도시 애스터로이드 시티. 매년 운석이 떨어진 것을 기념하는 소행성의 날 행사에 모인 사람들은 예상치 못한 사건으로 인해 그 곳에 옴짝달싹도 못한 채 갇히게 되고 계속해서 생각지도 못한 예측불허 상황들이 펼쳐지는데…",
      popularity: 281.514,
      poster_path: "/hmqczDa2B81Znu4QUUxCv8I6Yfd.jpg",
      release_date: "2023-06-28",
      title: "애스터로이드 시티",
      video: false,
      vote_average: 6.7,
      vote_count: 383,
    },
    {
      adult: false,
      backdrop_path: "/35z8hWuzfFUZQaYog8E9LsXW3iI.jpg",
      genre_ids: [12, 28, 14],
      id: 335977,
      original_language: "en",
      original_title: "Indiana Jones and the Dial of Destiny",
      overview:
        "1969년 뉴욕, 전설적인 모험가이자 고고학자 인디아나 존스 앞에 대녀 헬레나와 오랜 숙적 위르겐 폴러의 세력이 등장한다. 그들의 목표는 단 하나, 운명의 다이얼. 역사의 흐름을 바꿀 수 있는 다이얼을 차지하려는 쫓고 쫓기는 위협 속에 인디아나 존스는 전 세계를 무대로 하는 새로운 모험에 뛰어드는데…",
      popularity: 323.156,
      poster_path: "/8ifAx8GS5AHL7xOTMJDMaza84RQ.jpg",
      release_date: "2023-06-28",
      title: "인디아나 존스: 운명의 다이얼",
      video: false,
      vote_average: 6.6,
      vote_count: 747,
    },
    {
      adult: false,
      backdrop_path: "/gJjSWUYHCulhJS5LBQmEEKmkpyD.jpg",
      genre_ids: [16, 10751, 14, 35],
      id: 1040148,
      original_language: "en",
      original_title: "Ruby Gillman, Teenage Kraken",
      overview:
        "평범함 뒤에 숨겨진 능력을 가진 반전캐 크라켄 ‘루비’와  검은 속마음을 숨긴 사기캐 빌런 인어 ‘첼시’의 대결을 그린 드림웍스 제작진의 썸머 오션 어드벤처!",
      popularity: 368.775,
      poster_path: "/pUv9neufsz8hsXoIN5KkAeNZLgl.jpg",
      release_date: "2023-07-25",
      title: "틴에이지 크라켄 루비",
      video: false,
      vote_average: 7,
      vote_count: 95,
    },
    {
      adult: false,
      backdrop_path: "/sp7MPK2K60LLd7A6zjHKsfgjFil.jpg",
      genre_ids: [27, 14, 878, 53],
      id: 296271,
      original_language: "en",
      original_title: "The Devil Conspiracy",
      overview:
        "토리노 박물관에서 전시 중이던 예수 그리스도의 시신을 감쌌던 수의가 강탈되는 장면을 목격하면서 미국에서 유학 온 예술대 학생 로라의 운명이 참극으로 치닫게 된다. 로라에게 착상한 생명은 사탄인가, 재림 예수인가?",
      popularity: 118.952,
      poster_path: "/AdkReuLR9vumTzuFGTl9UBkpLTN.jpg",
      release_date: "2023-06-08",
      title: "악마의 부활",
      video: false,
      vote_average: 6.3,
      vote_count: 205,
    },
    {
      adult: false,
      backdrop_path: "/x9d7iSZNn6LNBzYHbM6x0vhrCPW.jpg",
      genre_ids: [53, 28, 35],
      id: 1057001,
      original_language: "ko",
      original_title: "귀공자",
      overview:
        "필리핀에서 불법 경기장을 전전하며 병든 어머니와 살아가는 복싱 선수 마르코. 어머니의 수술비 마련을 위해 평생 본 적 없는 아버지를 만나러 한국으로 향하던 그의 앞에 정체불명의 남자 귀공자가 나타나 그를 추격하기 시작한다. 마르코 주위를 쑥대밭으로 만들며 숨통을 조여오는 귀공자를 필두로, 아버지의 막대한 유산을 차지하기 위해 마르코를 추격하는 재벌 2세 한이사, 필리핀에 이어 한국에서 우연히 마르코와 재회한 미스터리한 여자 윤주까지. 각기 다른 목적을 가진 이들은 단 하나의 타겟을 쫓아 모여들고, 그 무엇도 예측할 수 없는 혼란과 광기 속 마르코는 충격적인 진실을 마주하게 되는데…  단 하나의 타겟, 광기의 추격이 시작된다!",
      popularity: 110.444,
      poster_path: "/nMyM7CpWoebu03mAI3JtKTwh5zm.jpg",
      release_date: "2023-06-21",
      title: "귀공자",
      video: false,
      vote_average: 7.9,
      vote_count: 5,
    },
    {
      adult: false,
      backdrop_path: "/o3YleBe0QGNNlUqm6CnJVqGQQH4.jpg",
      genre_ids: [35, 12, 14],
      id: 798286,
      original_language: "en",
      original_title: "Beau Is Afraid",
      overview:
        "아버지가 누군지 모른 채 사랑하는 독단적인 어머니와 살며 상처받은 중년 남자 보는 매사 두렵고 불안하지만 그렇지 않은 척하기 일쑤이다. 그런 그가 어머니를 만나러 고향으로 돌아가던 길에 초현실적인 상황과 직면하게 되는데…",
      popularity: 67.679,
      poster_path: "/pU8F9qKSoiqcv1nnaYezBzp7MoZ.jpg",
      release_date: "2023-07-05",
      title: "보 이즈 어프레이드",
      video: false,
      vote_average: 6.9,
      vote_count: 416,
    },
    {
      adult: false,
      backdrop_path: "/9lIK95xch2fGQEVnBw7BwQMjP8z.jpg",
      genre_ids: [18, 12, 878, 10751],
      id: 864101,
      original_language: "ru",
      original_title: "Мира",
      overview:
        "‘우주정거장 미르’에서는 24시간 뒤 지나갈 소행성을 추적 중 운석 충돌 가능성을 말하지만 무시되고 만다.  한편 지구에서는 이러한 영문도 모른 채  지구를 비켜갈 화려한 유성우의 우주쇼를 볼 기대에 들떠 있다.  그 시각, 소행성 뒤편 사각 지대의 운석 파편들이 핵폭탄보다 10배 강력한 파워로 우주정거장을 파괴한 후 지구를 향해 나아가고 소행성에 강타당한 지구는 모든 건물과 도로가 붕괴되며 대재앙이 펼쳐지는데...",
      popularity: 64.833,
      poster_path: "/oYy2fIQBxp1IlQ6oqE6KQoTXqD.jpg",
      release_date: "2023-07-05",
      title: "플래닛",
      video: false,
      vote_average: 6.5,
      vote_count: 17,
    },
    {
      adult: false,
      backdrop_path: "/uKTkiw3w3LfdzgiPOvu0C19Voi3.jpg",
      genre_ids: [16, 28, 80, 9648],
      id: 1047041,
      original_language: "ja",
      original_title: "名探偵コナン 黒鉄の魚影（サブマリン）",
      overview:
        "인터폴의 최첨단 정보 해양 시설인 퍼시픽 부이. 일본과 유럽의 CCTV 정보를 확인할 수 있을 뿐 아니라, 장기 수배범이나 유괴당한 피해자를 전 세계에서 찾아낼 수 있는 전연령 인식이라는 획기적인 AI 기술을 개발 중이다. 그러던 중 독일에서 검은 조직에 의해 유로폴 직원이 살해되는 사건이 발생하고 뒤를 이어 전연령 인식의 핵심 기술자가 납치된다. 나이와 상관없이 안면 인식이 가능한 기술이 검은 조직의 손에 들어가면 독약 APTX4869 개발 후 사망한 것으로 알려진 코드명 셰리이자 하이바라 아이도 위험하게 되는데...",
      popularity: 65.793,
      poster_path: "/wBdLreR2YI2ZAYGk7c4Zy2qJU2d.jpg",
      release_date: "2023-07-20",
      title: "명탐정 코난: 흑철의 어영",
      video: false,
      vote_average: 6.2,
      vote_count: 17,
    },
    {
      adult: false,
      backdrop_path: "/mmd1HnuvAzFc4iuVJcnBrhDNEKr.jpg",
      genre_ids: [27, 53],
      id: 694,
      original_language: "en",
      original_title: "The Shining",
      overview:
        "소설가인 잭 토랜스는 콜로라도 산맥에 있는 오버룩 호텔의 관리인으로 취직한다. 다음 시즌 준비를 하는 이곳은 겨울 동안 폐쇄되기 때문에 토랜스의 가족들만 호텔에 머물게 된다. 갑자기 몰아친 폭설로 잭과 아내 웬디와 아들과 함께 호텔에 고립되고, 투시와 텔레파시 능력이 있는 잭의 아들 대니는 호텔에 유령이 있으며 유령들이 천천히 아버지를 미치게 하고 있음을 알게 된다. 잭은 과거에 스스로 자신의 아내와 두 딸을 죽인 이곳의 예전 관리인 그레이디의 유령을 만난다. 과거에 있었던 살인사건의 악령에 휘말린 잭은 호텔을 공포의 도가니로 몰아가는데...",
      popularity: 42.863,
      poster_path: "/e3pxD5asVzFMcH3UvmGxolZ7wS.jpg",
      release_date: "2023-06-28",
      title: "샤이닝",
      video: false,
      vote_average: 8.2,
      vote_count: 15928,
    },
    {
      adult: false,
      backdrop_path: "/xH1fADDlEQMXreGClUCxA0XrJPC.jpg",
      genre_ids: [35, 10749],
      id: 982271,
      original_language: "en",
      original_title: "Book Club: The Next Chapter",
      overview:
        "한동안 세상이 멈추면서 만나지 못했던 북 클럽 4인방. 오랜만에 다시 모인 자리에서 비비안이 약혼 소식을 전하고 그런 비비안을 위한 싱글파티의 일환으로 이탈리아 여행을 계획한다. 로마부터 베니스까지, 불타는 청춘 못지 않게 여행하던 이들은 비비안이 주인공인 중요한 일정을 위해 마지막 여행지인 토스카나로 향한다. 그러나 이들 앞에 예상치 못한 일이 벌어지면서 발이 묶이는 위기에 처하는데…",
      popularity: 44.912,
      poster_path: "/mKjr1fRB6hjVi2XISVEmp5SVRIy.jpg",
      release_date: "2023-06-07",
      title: "북 클럽: 넥스트 챕터",
      video: false,
      vote_average: 6.8,
      vote_count: 69,
    },
    {
      adult: false,
      backdrop_path: "/5iMLD2KE0JQcPchegqSpKstU4CT.jpg",
      genre_ids: [18],
      id: 806368,
      original_language: "en",
      original_title: "The Son",
      overview:
        "성공한 변호사로 뉴욕에서 행복한 새 가정을 이룬 피터는 어느 날, 전처에게 아들 니콜라스가 학교를 나가지 않는다는 소식을 듣는다. 좋은 아버지가 되고 싶었던 피터는 아들을 집으로 데려오지만 애를 쓸수록 두 사람의 사이는 어긋나기만 하는데…",
      popularity: 50.424,
      poster_path: "/yEte5dcKGzcE6N3ZBRlVB8xLtlP.jpg",
      release_date: "2023-07-19",
      title: "더 썬",
      video: false,
      vote_average: 6.7,
      vote_count: 238,
    },
    {
      adult: false,
      backdrop_path: "/fRrpOILyXuWaWLmqF7kXeMVwITQ.jpg",
      genre_ids: [27, 28, 12],
      id: 522444,
      original_language: "en",
      original_title: "Black Water: Abyss",
      overview:
        "호주의 깊은 숲 속. 외딴 동굴 탐험에 나선 제니퍼와 에릭, 그리고 친구들은 폭풍우로 인해 불어난 물로 동굴에 갇히게 된다.  제한된 식량과 시간 속에서 탈출구를 찾던 그들에게 불길한 그림자가 서서히 드리우는데...  미로처럼 뻗어 나가는 동굴 속  그들은 과연 살아서 동굴을 탈출할 수 있을까?",
      popularity: 54.072,
      poster_path: "/8nYyl8WJE9BXPaBsjZglzJo36FP.jpg",
      release_date: "2023-06-14",
      title: "블랙 워터: 어비스",
      video: false,
      vote_average: 5.2,
      vote_count: 389,
    },
    {
      adult: false,
      backdrop_path: "/kpzDQtFbw3dWoFxabydK9tlvWJm.jpg",
      genre_ids: [16, 10751],
      id: 778810,
      original_language: "en",
      original_title: "Fireheart",
      overview:
        "1932년 뉴욕, 브로드웨이 극장가를 노리는 연쇄 방화 사건 발생! 800명의 소방관이 실종되는 전대미문의 사건으로 혼란에 빠진 뉴욕의 ‘지미 시장’은 은퇴한 소방관 ‘숀’을 다시 불러 긴급 소방팀을 꾸린다. 어릴 때부터 아버지 ‘숀’처럼 멋진 소방관이 되고 싶은 꿈을 가진 ‘조지아’는 초보 소방관 ‘조’로 감쪽같이 변장해 긴급 소방팀에 몰래 합류하는 데 성공하는데… 방화범을 잡기 위한 소방 대작전 개시! 의욕은 충만! 실전 경험 전무! 과연 조지아와 초보 소방팀은 최악의 위기에 처한 뉴욕시를 구할 수 있을 것인가..!",
      popularity: 38.478,
      poster_path: "/1VQHNwsuLdCiXgPpWqPz0yKUyB4.jpg",
      release_date: "2023-06-28",
      title: "파이어하트",
      video: false,
      vote_average: 7.4,
      vote_count: 214,
    },
    {
      adult: false,
      backdrop_path: "/7vxuOzbsDgGRKNiB9yzvSHaNlNi.jpg",
      genre_ids: [16, 12, 878],
      id: 1030587,
      original_language: "ja",
      original_title: "映画ドラえもん のび太と空の理想郷",
      overview:
        "어느 날, 하늘 위 떠있는 초승달 모양의 섬을 발견한 진구는 그곳이 자신이 찾고 있던 유토피아가 틀림없다고 생각한다. 그렇게 시공을 초월하는 비행선 ‘타임 제플린’을 타고 섬을 찾아 떠나기로 한 도라에몽과 친구들.여러 시대와 장소를 헤매다 드디어 누구나 완벽해질 수 있는 꿈같은 낙원 ‘파라다피아’에 도착한다. 그곳에서 모든 게 완벽한 퍼펙트 고양이형 로봇 ‘소냐’와 만나 친구가 되지만, 이 낙원에 엄청난 비밀이 숨겨져 있다는 것을 알게 되는데..! 무엇이든 이루어지는 낙원의 섬 ‘파라다피아’의 숨겨진 비밀을 찾기 위한 도라에몽과 친구들의 짜릿한 대모험이 시작된다!",
      popularity: 35.498,
      poster_path: "/pMfGiIseOHHqTXKsL1PanAjFKQv.jpg",
      release_date: "2023-07-08",
      title: "극장판 도라에몽: 진구와 하늘의 유토피아",
      video: false,
      vote_average: 6.9,
      vote_count: 12,
    },
  ],
  total_pages: 5,
  total_results: 91,
};
